import { ExternalLink, Image as ImageIcon, UserRoundCheck } from "lucide-react";
import Link from "next/link";
import { updateDiscoveryResearchAction } from "@/app/actions/discovery";
import { DiscoveryTabs } from "@/components/discovery-tabs";
import { buttonStyles } from "@/components/ui/button";
import { requireUser } from "@/lib/auth";
import { getResearchItems } from "@/lib/discovery/data";
import { cn, formatDate } from "@/lib/utils";
import { discoveryResearchStatuses, researchStatusLabels, sourceTypeLabels, type DiscoveryResearchStatus } from "@/types/discovery";

export default async function ResearchQueuePage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const user = await requireUser();
  const params = await searchParams;
  const status = discoveryResearchStatuses.includes(params.status as DiscoveryResearchStatus) ? params.status as DiscoveryResearchStatus : undefined;
  const items = await getResearchItems(status);
  return <>
    <header><p className="text-[10px] font-medium tracking-[0.18em] text-muted uppercase">Candidate research</p><h1 className="mt-2 text-3xl font-medium tracking-[-0.045em] sm:text-4xl">Research Queue</h1><p className="mt-2 text-sm text-muted">公開情報の確認状況、担当、次に必要な情報を管理します。</p></header>
    <DiscoveryTabs current="research" />
    <div className="mt-5 flex gap-2 overflow-x-auto"><Link href="/discovery/research" className={cn("rounded-full border bg-surface px-3 py-1.5 text-xs text-muted", !status && "border-foreground text-foreground")}>All</Link>{discoveryResearchStatuses.map((value) => <Link key={value} href={`/discovery/research?status=${value}`} className={cn("whitespace-nowrap rounded-full border bg-surface px-3 py-1.5 text-xs text-muted", status === value && "border-foreground text-foreground")}>{researchStatusLabels[value]}</Link>)}</div>
    {items.length ? <div className="mt-5 grid gap-4 xl:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-xl border bg-surface p-4 sm:p-5"><div className="flex gap-4"><div className="grid size-20 shrink-0 place-items-center overflow-hidden rounded-lg bg-surface-muted bg-cover bg-center" style={item.thumbnail_url ? { backgroundImage: `url(${JSON.stringify(item.thumbnail_url).slice(1, -1)})` } : undefined}>{item.thumbnail_url ? null : <ImageIcon size={18} className="text-muted" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-surface-muted px-2 py-1 text-[10px]">{sourceTypeLabels[item.source_type]}</span><span className="rounded-full border px-2 py-1 text-[10px]">{researchStatusLabels[item.research_status]}</span><span className="ml-auto font-mono text-xs">DQ {item.research_quality_score}</span></div><h2 className="mt-3 truncate text-base font-medium">{item.author_name}</h2><p className="mt-1 truncate text-xs text-muted">{item.country || "地域未確認"} · {item.software.length ? item.software.join(" / ") : "ソフト未確認"}</p></div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border bg-[#faf9f5] p-3"><p className="text-[10px] text-muted">次に確認</p><p className="mt-2 text-xs leading-5">{item.next_required_fields.length ? item.next_required_fields.slice(0, 4).join("、") : "必須情報は揃っています"}</p></div><div className="rounded-lg border bg-[#faf9f5] p-3"><p className="text-[10px] text-muted">AI仮評価</p><p className="mt-2 text-xs">{item.preliminary_ai_evaluation ? `評価済み ${item.preliminary_ai_score ?? "—"}` : item.research_status === "ready_for_ai_review" ? "実行待ち" : "未評価"}</p></div></div>
      <div className="mt-4 flex flex-wrap gap-2 text-[10px] text-muted"><span>担当：{item.assigned_to ? item.assigned_to === user.id ? "自分" : `${item.assigned_to.slice(0, 8)}…` : "未割当"}</span><span>最終確認：{item.last_verified_at ? formatDate(item.last_verified_at) : "未確認"}</span><Link href={`/discovery/research/${item.id}`} className="ml-auto text-foreground underline underline-offset-4">作品・AI条件</Link></div>
      <form action={updateDiscoveryResearchAction.bind(null, item.id)} className="mt-4 border-t pt-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><select name="research_status" defaultValue={item.research_status} className="h-10 rounded-lg border bg-white px-3 text-xs">{discoveryResearchStatuses.map((value) => <option key={value} value={value}>{researchStatusLabels[value]}</option>)}</select><button className={buttonStyles("secondary", "h-10 px-4 text-xs")}>更新</button></div><textarea name="notes_for_review" defaultValue={item.notes_for_review ?? ""} maxLength={5000} rows={2} placeholder="確認メモ（AIには送信しません）" className="mt-3 w-full rounded-lg border bg-white px-3 py-2 text-xs" /><div className="mt-3 flex flex-wrap items-center gap-4 text-xs"><label className="flex items-center gap-2"><input type="checkbox" name="assign_to_me" defaultChecked={item.assigned_to === user.id} className="accent-[#252522]" /><UserRoundCheck size={13} />自分を担当にする</label><label className="flex items-center gap-2"><input type="checkbox" name="verified_now" className="accent-[#252522]" />今確認した</label><a href={item.portfolio_url || item.source_url} target="_blank" rel="noreferrer" className="ml-auto flex items-center gap-1 text-muted hover:text-foreground"><ExternalLink size={12} />公開ページ</a></div></form>
    </article>)}</div> : <section className="mt-6 rounded-xl border bg-surface px-6 py-20 text-center"><h2 className="text-sm font-medium">調査対象はありません</h2><p className="mt-2 text-xs text-muted">AcquisitionからURLまたはCSVを登録してください。</p></section>}
  </>;
}
