import type { ReferenceMetric } from "@/lib/visual-search/reference-analysis";

type Summary = { overallCharacter: string; lighting: string; composition: string; materialLanguage: string; brandExpression: string; displayStrategy: string; colorStrategy: string; visualSilence: string; strengths: string[]; potentialRisks: string[] };

function MetricBar({ metric }: { metric: ReferenceMetric }) {
  return <div className="border-b py-3 last:border-0"><div className="flex items-baseline justify-between gap-4"><p className="text-xs font-medium">{metric.label}</p><p className="font-mono text-sm">{metric.value}<span className="text-[10px] text-muted">/100</span></p></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-line"><span className="block h-full rounded-full bg-foreground" style={{ width: `${metric.value}%` }}/></div><p className="mt-1.5 text-[9px] leading-4 text-muted">{metric.basis}</p></div>;
}

export function ReferenceAnalysis({ metadata, metrics, summary }: { metadata: Array<[string, string]>; metrics: ReferenceMetric[]; summary: Summary }) {
  const sections: Array<[string, string | string[]]> = [["Overall Character", summary.overallCharacter], ["Lighting", summary.lighting], ["Composition", summary.composition], ["Material Language", summary.materialLanguage], ["Brand Expression", summary.brandExpression], ["Display Strategy", summary.displayStrategy], ["Color Strategy", summary.colorStrategy], ["Visual Silence", summary.visualSilence], ["Strengths", summary.strengths], ["Potential Risks", summary.potentialRisks]];
  return <section className="mt-7 border-t pt-7"><div><p className="text-[10px] font-medium tracking-[.18em] text-muted uppercase">Reference Analysis</p><h2 className="mt-2 text-2xl font-medium tracking-[-.035em]">保存済み特徴量の分析</h2><p className="mt-2 text-xs leading-5 text-muted">元画像を再送信せず、保存済み構造化特徴だけを表示・マッピングしています。記述カバレッジは品質評価ではありません。</p></div><dl className="mt-6 grid border-y sm:grid-cols-2 xl:grid-cols-4">{metadata.map(([label, value]) => <div key={label} className="border-b px-0 py-3 sm:px-4 sm:first:pl-0 xl:border-b-0"><dt className="text-[9px] tracking-[.12em] text-muted uppercase">{label}</dt><dd className="mt-1 text-xs leading-5">{value || "—"}</dd></div>)}</dl><div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)]"><div><h3 className="text-sm font-medium">Feature Scores</h3><div className="mt-3 border-y">{metrics.map((metric) => <MetricBar key={metric.key} metric={metric}/>)}</div></div><div><h3 className="text-sm font-medium">Style Summary</h3><div className="mt-3 grid gap-x-7 border-y sm:grid-cols-2">{sections.map(([label, value]) => <div key={label} className="border-b py-4"><h4 className="text-[10px] font-medium tracking-[.1em] uppercase">{label}</h4>{Array.isArray(value) ? <ul className="mt-2 space-y-1 text-xs leading-5 text-muted">{value.map((item) => <li key={item}>— {item}</li>)}</ul> : <p className="mt-2 text-xs leading-5 text-muted">{value}</p>}</div>)}</div></div></div></section>;
}

