"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { RubricAxis } from "@/app/(workspace)/calibration/page";

export function RubricEditor({ rubricId, rubricName, version, axes: initialAxes, history }: { rubricId: string; rubricName: string; version: number; axes: RubricAxis[]; history: Array<{ version: number; note: string | null; publishedAt: string }> }) {
  const router = useRouter();
  const [axes, setAxes] = useState(initialAxes); const [note, setNote] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const total = axes.reduce((sum, axis) => sum + axis.weight, 0);
  function update(index: number, patch: Partial<RubricAxis>) { setAxes((current) => current.map((axis, axisIndex) => axisIndex === index ? { ...axis, ...patch } : axis)); }
  async function publish() { setPending(true); setMessage(null); try { const response = await fetch("/api/calibration/rubrics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ rubric_id: rubricId, axes, change_note: note }) }); const body = await response.json() as { error?: string; version?: number }; if (!response.ok) throw new Error(body.error || "保存できませんでした。"); setMessage(`version ${body.version}を公開しました。`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存できませんでした。"); } finally { setPending(false); } }
  return <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded-xl border bg-surface"><div className="flex items-center justify-between border-b bg-[#f8f7f2] px-5 py-4"><div><h2 className="text-sm font-medium">{rubricName}</h2><p className="mt-1 font-mono text-[10px] text-muted">current version {version}</p></div><span className={`font-mono text-xs ${total === 100 ? "text-[#596d5d]" : "text-danger"}`}>weight {total} / 100</span></div><div className="divide-y">{axes.map((axis, index) => <div key={axis.key} className="grid gap-4 p-5 lg:grid-cols-[180px_minmax(0,1fr)]"><div><p className="text-sm font-medium">{axis.label}</p><p className="mt-1 font-mono text-[10px] text-muted">{axis.key}</p><label className="mt-4 flex items-center gap-2 text-xs"><input type="checkbox" checked={axis.required} onChange={(event) => update(index, { required: event.target.checked })} className="accent-[#252522]" />必須軸</label><label className="mt-3 block text-xs text-muted">重み<input type="number" min={1} max={50} value={axis.weight} onChange={(event) => update(index, { weight: Number(event.target.value) })} className="mt-1 h-9 w-full rounded-lg border bg-white px-3 font-mono text-xs" /></label></div><div className="grid gap-3 sm:grid-cols-3"><EditArea label="説明" value={axis.description} onChange={(value) => update(index, { description: value })} /><EditArea label="良い例" value={axis.good_example} onChange={(value) => update(index, { good_example: value })} /><EditArea label="懸念例" value={axis.concern_example} onChange={(value) => update(index, { concern_example: value })} /></div></div>)}</div></section><aside className="space-y-5"><section className="rounded-xl border bg-surface p-5"><h2 className="text-sm font-medium">新versionを公開</h2><p className="mt-2 text-xs leading-5 text-muted">過去versionは変更せず、次回AI評価から新基準を保存します。</p><textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} rows={4} placeholder="変更理由" className="mt-4 w-full rounded-lg border bg-white px-3 py-2 text-xs" /><Button className="mt-3 w-full" disabled={pending || total !== 100 || !note.trim()} onClick={publish}>{pending ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />}version {version + 1}を公開</Button>{message ? <p className="mt-3 text-xs text-muted">{message}</p> : null}</section><section className="rounded-xl border bg-[#f8f7f2] p-5"><h2 className="text-xs font-medium">Version history</h2><div className="mt-3 space-y-3">{history.slice(0, 8).map((item) => <div key={item.version} className="border-t pt-3 first:border-0 first:pt-0"><p className="font-mono text-xs">v{item.version}</p><p className="mt-1 text-[11px] leading-5 text-muted">{item.note || "変更メモなし"}</p></div>)}</div></section></aside></div>;
}

function EditArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-[10px] text-muted">{label}<textarea value={value} onChange={(event) => onChange(event.target.value)} maxLength={1000} rows={5} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-xs leading-5 text-foreground" /></label>; }
