"use client";
import { useState } from "react";
import { FlaskConical, Loader2, Play } from "lucide-react";
import { buttonStyles } from "@/components/ui/button";
import { fieldControlClass } from "@/components/ui/field";

type CandidateOption = { id: string; full_name: string };
type TestCase = { id: string; name: string; query: string; scout_test_runs?: Array<{ id: string; precision_at_3: number | null; precision_at_5: number | null; sample_size: number; sample_status: string; executed_at: string; status: string }> };
export function ScoutTestManager({ candidates, cases }: { candidates: CandidateOption[]; cases: TestCase[] }) {
  const [name, setName] = useState(""); const [query, setQuery] = useState(""); const [expected, setExpected] = useState<string[]>([]); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const create = async () => { setBusy("create"); const r = await fetch("/api/scout/tests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, query, expected_ids: expected }) }); const p = await r.json(); setBusy(""); setMessage(r.ok ? "保存しました。" : p.error); if (r.ok) window.location.reload(); };
  const run = async (id: string) => { setBusy(id); const r = await fetch("/api/scout/tests", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); const p = await r.json(); setBusy(""); setMessage(r.ok ? (p.run.sample_status === "insufficient" ? "実行しました。サンプル不足のため精度は確定しません。" : "評価を実行しました。") : p.error); if (r.ok) window.location.reload(); };
  return <div className="mt-7 grid gap-6 lg:grid-cols-[380px_1fr]"><section className="rounded-xl border bg-surface p-5"><h2 className="text-sm font-medium">テストケースを保存</h2><div className="mt-4 space-y-3"><input className={fieldControlClass} value={name} onChange={(e) => setName(e.target.value)} placeholder="例: TASAKIの高級店舗案件" maxLength={160}/><textarea className={`${fieldControlClass} min-h-28`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="自然言語の検索条件" maxLength={1200}/><label className="block text-xs text-muted">想定上位候補（Ctrl / ⌘で複数選択）</label><select multiple className={`${fieldControlClass} min-h-28`} value={expected} onChange={(e) => setExpected(Array.from(e.target.selectedOptions, (o) => o.value))}>{candidates.map((c) => <option key={c.id} value={c.id}>{c.full_name}</option>)}</select><button className={buttonStyles("primary", "w-full")} disabled={busy === "create" || !name || query.length < 5} onClick={create}>{busy === "create" ? <Loader2 size={14} className="animate-spin"/> : <FlaskConical size={14}/>}保存</button></div></section><section className="space-y-3">{cases.length ? cases.map((item) => { const last = item.scout_test_runs?.[0]; return <article key={item.id} className="rounded-xl border bg-surface p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-medium">{item.name}</h3><p className="mt-1 text-sm text-muted">{item.query}</p></div><button className={buttonStyles("secondary", "shrink-0")} onClick={() => run(item.id)} disabled={busy === item.id}>{busy === item.id ? <Loader2 className="animate-spin" size={14}/> : <Play size={14}/>}実行</button></div>{last ? <div className="mt-4 grid grid-cols-2 gap-3 border-t pt-4 sm:grid-cols-4"><div><p className="text-[10px] text-muted">Precision@3</p><p className="mt-1 font-mono">{last.precision_at_3 === null ? "—" : last.precision_at_3.toFixed(2)}</p></div><div><p className="text-[10px] text-muted">Precision@5</p><p className="mt-1 font-mono">{last.precision_at_5 === null ? "—" : last.precision_at_5.toFixed(2)}</p></div><div><p className="text-[10px] text-muted">候補者数</p><p className="mt-1 font-mono">{last.sample_size}</p></div><div><p className="text-[10px] text-muted">評価状態</p><p className="mt-1 text-xs font-medium text-amber-700">{last.sample_status === "insufficient" ? "サンプル不足" : "評価可能"}</p></div></div> : <p className="mt-4 border-t pt-4 text-xs text-muted">未実行</p>}</article>}) : <div className="rounded-xl border bg-surface px-6 py-16 text-center text-sm text-muted">テストケースはまだありません。</div>}{message ? <p className="text-xs text-muted">{message}</p> : null}</section></div>;
}
