"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Copy, ExternalLink, Loader2, Pencil, RotateCcw, Trash2 } from "lucide-react";
import { buttonStyles } from "@/components/ui/button";

export function VisualSearchControls({ searchId, searchName, showOpen = false, compact = false }: { searchId: string; searchName?: string; showOpen?: boolean; compact?: boolean }) {
  const router = useRouter(); const [action, setAction] = useState<"rerun" | "duplicate" | "rename" | "delete" | null>(null); const [error, setError] = useState("");
  const size = compact ? "h-8 px-2 text-[11px]" : "h-9 px-3 text-xs";
  async function rerun() { setAction("rerun"); setError(""); try { const response = await fetch(`/api/visual-search/${searchId}/run`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode: "rerun" }), cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); router.push(`/visual-search/${searchId}`); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "再実行できませんでした。"); } finally { setAction(null); } }
  async function duplicate() { setAction("duplicate"); setError(""); try { const response = await fetch(`/api/visual-search/${searchId}/duplicate`, { method: "POST", headers: { "content-type": "application/json" } }); const body = await response.json(); if (!response.ok) throw new Error(body.error); router.push(`/visual-search/${body.id}`); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "複製できませんでした。"); } finally { setAction(null); } }
  async function rename() { const name = window.prompt("新しい検索名", searchName ?? ""); if (!name?.trim()) return; setAction("rename"); setError(""); try { const response = await fetch(`/api/visual-search/${searchId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: name.trim() }), cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "名前を変更できませんでした。"); } finally { setAction(null); } }
  async function remove() { if (!window.confirm("特徴量、分析結果、検索履歴を削除しますか？")) return; setAction("delete"); setError(""); try { const response = await fetch(`/api/visual-search/${searchId}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); router.push("/visual-search"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "削除できませんでした。"); } finally { setAction(null); } }
  return <div><div className="flex flex-wrap items-center gap-2">{showOpen ? <Link href={`/visual-search/${searchId}`} className={buttonStyles("secondary", size)}><ExternalLink size={13}/>開く</Link> : null}<button type="button" onClick={rerun} disabled={action !== null} className={buttonStyles("secondary", size)}>{action === "rerun" ? <Loader2 size={13} className="animate-spin"/> : <RotateCcw size={13}/>}保存済み特徴量で再検索</button><button type="button" onClick={duplicate} disabled={action !== null} className={buttonStyles("ghost", size)}>{action === "duplicate" ? <Loader2 size={13} className="animate-spin"/> : <Copy size={13}/>}複製</button><button type="button" onClick={rename} disabled={action !== null} className={buttonStyles("ghost", size)}>{action === "rename" ? <Loader2 size={13} className="animate-spin"/> : <Pencil size={13}/>}名前変更</button><button type="button" onClick={remove} disabled={action !== null} className={buttonStyles("ghost", `${size} text-danger`)}>{action === "delete" ? <Loader2 size={13} className="animate-spin"/> : <Trash2 size={13}/>}削除</button></div><p className="mt-2 text-[10px] text-muted">元画像は破棄済みです。複製・再検索には保存済み特徴量だけを使用します。</p>{error ? <p role="alert" className="mt-2 text-xs text-danger">{error}</p> : null}</div>;
}
