import { ExternalLink, Pause, Play } from "lucide-react";
import { createDiscoverySourceAction, toggleDiscoverySourceAction } from "@/app/actions/discovery";
import { DiscoveryTabs } from "@/components/discovery-tabs";
import { Button, buttonStyles } from "@/components/ui/button";
import { Field, fieldControlClass } from "@/components/ui/field";
import { getDiscoveryRuns, getDiscoverySources } from "@/lib/discovery/data";
import { sourceTypeLabels } from "@/types/discovery";

export default async function DiscoverySourcesPage() {
  const [sources, runs] = await Promise.all([getDiscoverySources(), getDiscoveryRuns()]);
  return <>
    <header><p className="text-[10px] font-medium tracking-[0.18em] text-muted uppercase">Discovery control</p><h1 className="mt-2 text-3xl font-medium tracking-[-0.045em] sm:text-4xl">検索テーマ</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">1テーマ最大20件/日。BehanceはRecruiter Proでの手動探索、または保存権を含む契約済み検索APIだけを使用します。</p></header>
    <DiscoveryTabs current="sources" />
    <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]">
      <section className="rounded-xl border bg-surface p-5 sm:p-7"><h2 className="text-lg font-medium">登録済みテーマ</h2><div className="mt-5 space-y-3">{sources.length ? sources.map((source) => <article key={source.id} className="flex flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="rounded-full bg-surface-muted px-2 py-1 text-[10px]">{sourceTypeLabels[source.source_type]}</span><span className={`size-1.5 rounded-full ${source.enabled ? "bg-[#63836a]" : "bg-[#aaa8a0]"}`} /></div><h3 className="mt-2 font-medium">{source.name}</h3><p className="mt-1 truncate text-xs text-muted">{source.search_query}</p><p className="mt-2 font-mono text-[10px] text-muted">上限 {source.daily_limit}/日 · 最終実行 {source.last_run_at ? new Date(source.last_run_at).toLocaleString("ja-JP") : "未実行"}</p></div><div className="flex gap-2">{source.source_type === "behance" ? <a href={`https://www.behance.net/search/projects?search=${encodeURIComponent(source.search_query)}`} target="_blank" rel="noreferrer" className={buttonStyles("secondary", "h-8 px-3 text-xs")}><ExternalLink size={13} />Behanceで検索</a> : null}<form action={toggleDiscoverySourceAction.bind(null, source.id, !source.enabled)}><button className={buttonStyles("ghost", "h-8 px-2 text-xs")} aria-label={source.enabled ? "一時停止" : "有効化"}>{source.enabled ? <Pause size={13} /> : <Play size={13} />}</button></form></div></article>) : <p className="py-12 text-center text-sm text-muted">検索テーマはまだありません。</p>}</div></section>
      <section className="rounded-xl border bg-surface p-5 sm:p-7"><h2 className="text-lg font-medium">テーマを追加</h2><form action={createDiscoverySourceAction} className="mt-5 space-y-4"><Field label="テーマ名" htmlFor="name"><input id="name" name="name" required placeholder="Luxury retail archviz" className={fieldControlClass} /></Field><Field label="ソース" htmlFor="source_type"><select id="source_type" name="source_type" defaultValue="behance" className={fieldControlClass}><option value="behance">Behance</option><option value="artstation">ArtStation</option><option value="website">Webサイト</option><option value="manual">手動</option></select></Field><Field label="検索クエリ" htmlFor="search_query"><textarea id="search_query" name="search_query" required rows={3} placeholder="luxury retail interior 3ds max corona" className={fieldControlClass} /></Field><div className="grid grid-cols-2 gap-4"><Field label="国ヒント" htmlFor="country_hint"><input id="country_hint" name="country_hint" className={fieldControlClass} /></Field><Field label="1日上限" htmlFor="daily_limit"><input id="daily_limit" name="daily_limit" type="number" min="1" max="20" defaultValue="10" className={fieldControlClass} /></Field></div><Button type="submit">テーマを追加</Button></form></section>
    </div>
    <section className="mt-5 rounded-xl border bg-surface p-5 sm:p-7"><h2 className="text-lg font-medium">実行履歴</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b text-muted"><tr><th className="py-3 font-medium">開始</th><th className="font-medium">テーマ</th><th className="font-medium">状態</th><th className="font-medium">検出</th><th className="font-medium">新規</th><th className="font-medium">重複</th><th className="font-medium">メッセージ</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-b last:border-0"><td className="py-3 font-mono">{new Date(run.started_at).toLocaleString("ja-JP")}</td><td>{run.discovery_sources?.name ?? "全体"}</td><td>{run.status}</td><td>{run.items_found}</td><td>{run.items_created}</td><td>{run.duplicates_found}</td><td className="max-w-72 truncate text-muted">{run.error_message ?? "—"}</td></tr>)}</tbody></table></div></section>
  </>;
}
